@startuml
left to right direction

usecase フロアマップの追加
actor 担当者
entity フロアマップ
boundary 一覧画面
control 一覧画面表示
control 作成画面表示
boundary 作成画面
control フロアマップ追加

フロアマップの追加 . 担当者
担当者 --> 一覧画面: 1.アクセスする\n4.登録ボタンを\nクリックする >
一覧画面表示 --> フロアマップ: 2.読み取る
一覧画面 <-- 一覧画面表示: 3.表示する
一覧画面 --> 作成画面表示: 5.呼び出す
作成画面 <-- 作成画面表示: 6.表示する
担当者 --> 作成画面: 7.入力して\n保存ボタンを\nクリックする >
作成画面 --> フロアマップ追加: 8.呼び出す
フロアマップ追加 --> フロアマップ: 9.追加する

@enduml