@startuml
left to right direction

usecase フロアマップの変更
actor 担当者
entity フロアマップ
boundary 一覧画面
control 一覧画面表示
control フロアマップ更新
control 編集画面表示
boundary 編集画面

フロアマップの変更 . 担当者
担当者 --> 一覧画面: 1.アクセスする\n4.編集ボタンを\nクリックする >
一覧画面 <-- 一覧画面表示 : 3.表示する <
一覧画面表示 --> フロアマップ : 2.読み取る >
一覧画面 --> 編集画面表示: 5.呼び出す >
編集画面 <-- 編集画面表示 : 7.表示する <
編集画面表示 --> フロアマップ : 6.読み取る >
担当者 --> 編集画面 : 8.編集して保存ボタン\nをクリックする >
編集画面 --> フロアマップ更新: 9.呼び出す >
フロアマップ更新 --> フロアマップ: 10.更新する >
'フロアマップ更新 -> 一覧画面表示: 11.遷移する >

@enduml