@startuml
title 【総務部】
|フロアレイアウト担当者|
:フロア増床;
:レイアウトデータ追加;

|せつでんくん担当者|
:フロアマップ画像作成;
:フロアマップの追加;
note right: (UC) フロアマップを追加する
detach

|フロアレイアウト担当者|
:フロアレイアウト変更;
:レイアウトデータ更新;

|せつでんくん担当者|
:フロアマップ画像再作成;
:新しいフロアマップ画像の反映;
note right: (UC) フロアマップ画像を更新する
detach


|フロアレイアウト担当者|
:フロア削減;
:レイアウトデータ削除;

|せつでんくん担当者|
:フロアマップの削除;
note right: (UC) フロアマップを削除する
detach
@enduml