@startuml
left to right direction

usecase フロアマップの削除
actor 担当者
boundary 一覧画面
control 一覧画面表示
entity フロアマップ
control フロアマップ削除

フロアマップの削除 . 担当者
担当者 --> 一覧画面: 1.アクセスする\n4.フロアを選んで\n削除ボタンを\nクリックする
一覧画面 <-- 一覧画面表示: 3.表示する
一覧画面表示 --> フロアマップ: 2.読み取る
一覧画面 --> フロアマップ削除: 5.呼び出す
フロアマップ削除 --> フロアマップ: 6.削除する
フロアマップ削除 -l-> 一覧画面表示: 7.遷移する

@enduml
