@startuml
hide circle

class ユーザー {
  セッションID
  名前
}
class 室温情報 {
 # セッションID
 # フロア
  寒暖
  程度
}
class フロア {
  名称
  マップ画像
}
class 認証 {
 # フロア
  名前
  パスワード
}
class 管理者 {
}

室温情報 "0..*" -o "1" フロア : を持つ <
フロア "1" - "1" 認証 : を要求する >
認証 "1" o-- "0..*" ユーザー : をログインに利用する <
ユーザー "1" - "1" 室温情報 : を記録する >
管理者 -- フロア : を管理する >
管理者 -- 認証 : を更新する >

@enduml