@startuml
hide circle

class ユーザー {
  セッションID
}
class 体感室温 {
  # セッションID
  # フロアマップ
  座標
  寒暖（寒い or 暑い）
  程度（ちょっと or すごく）
  登録日時
  生存期間
}
class 座標 {
  X軸
  Y軸
}
class フロアマップ {
  # 会社
  名称
  マップ画像
  空調設定内容
}
class 空調設定内容 {
  # フロアマップ
  リモコン画像
}
class 認証 {
 # フロアマップ
  パスワード
}
class 管理者 {
  # 会社
  ログインID
  パスワード
}
class 会社 {
  名称
}

体感室温 "0..*" --o "1" フロアマップ : を持つ <
座標 "1" - "1" 体感室温 : の位置を表す >
フロアマップ "1" -- "1" 認証 : を要求する >
ユーザー "1" o-- "0..*" 認証  : でログインする >
体感室温 "1" -- "1" ユーザー : を表明する <
フロアマップ -- 管理者 : を管理する <
認証 - 管理者 : を管理する <
フロアマップ "1" o- "1..*" 空調設定内容 : を複数持つ >
会社 "1..*" o- 管理者 : に属する >
フロアマップ "1..*" -o "1" 会社 : に属する <

note left of ユーザー
ユーザーは匿名で参加でき、
フロアマップ名とパスワード
でログインする。
end note

@enduml