@startuml
left to right direction

actor 利用者
actor 総務部担当者
usecase "室温共有システム\nせつでんくん" as せつでんくん
component 空調

利用者 -- せつでんくん
総務部担当者 -- せつでんくん
せつでんくん -- 空調

note top of せつでんくん
= システム化の目的
フロアにいる利用者が寒暖の体感室温を共有することで、
空調の温度設定を変更しやすい環境を作り、
* 暑すぎや寒すぎの環境を改善する
* 無駄な電力消費を抑える
end note

@enduml