@startuml
left to right direction

usecase ログイン
actor 利用者
control ログイン画面表示
boundary ログイン画面
boundary 遷移先画面
control ユーザー認証
entity 認証情報

利用者 --> ログイン画面 : 1. アクセスする\n3. フロア名と\nパスワードを入力
ログイン画面表示 -> ログイン画面: 2. 表示する
ログイン画面 --> ユーザー認証: 4. 呼び出す
ユーザー認証 -- 認証情報

遷移先画面 <-- ユーザー認証 : 5. 認証後に\n遷移する

ログイン . 利用者
@enduml