@startuml
left to right direction
usecase ログイン
usecase 体感室温表明
actor 利用者
control ログイン済みか
boundary フロアマップ画面
control フロアマップ表示
entity フロアマップ
entity 体感室温情報
entity 空調設定内容

control 体感室温情報記録

体感室温表明 . 利用者
'利用者 -> フロアマップ画面
フロアマップ画面 --> ログイン済みか
ログイン済みか --> ログイン : no
フロアマップ表示 <-- ログイン
ログイン済みか -> フロアマップ表示 : yes

フロアマップ画面 <-- フロアマップ表示
フロアマップ表示 -- フロアマップ
フロアマップ表示 -- 体感室温情報
フロアマップ表示 - 空調設定内容
利用者 -> フロアマップ画面 : アクセスする\nアイコンを置く
フロアマップ画面 --> 体感室温情報記録 : 体感室温入力
体感室温情報記録 --> 体感室温情報
フロアマップ画面 <-- 体感室温情報記録 : アイコンを\n追加表示する


@enduml